-- AlterTable
ALTER TABLE "CONFIGURACION" ADD COLUMN     "DEVOLUCION_REINTEGRO" VARCHAR(20) NOT NULL DEFAULT 'PREGUNTAR',
ADD COLUMN     "DEVOLUCION_STOCK" VARCHAR(20) NOT NULL DEFAULT 'PREGUNTAR';

-- CreateTable
CREATE TABLE "DEVOLUCION" (
    "ID_DEVOLUCION" BIGSERIAL NOT NULL,
    "ID_PEDIDO" BIGINT NOT NULL,
    "FECHA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MOTIVO" VARCHAR(500) NOT NULL,
    "DEVUELVE_STOCK" BOOLEAN NOT NULL,
    "ID_PAGO_REINTEGRO" BIGINT,
    "ID_USUARIO" BIGINT,

    CONSTRAINT "DEVOLUCION_pkey" PRIMARY KEY ("ID_DEVOLUCION")
);

-- CreateTable
CREATE TABLE "DEVOLUCION_DETALLE" (
    "ID_DEVOLUCION_DETALLE" BIGSERIAL NOT NULL,
    "ID_DEVOLUCION" BIGINT NOT NULL,
    "ID_PEDIDO_DETALLE" BIGINT NOT NULL,
    "CANTIDAD" DECIMAL(18,3) NOT NULL,
    "PRECIO_UNITARIO" DECIMAL(18,2) NOT NULL,
    "SUBTOTAL" DECIMAL(18,2) NOT NULL,

    CONSTRAINT "DEVOLUCION_DETALLE_pkey" PRIMARY KEY ("ID_DEVOLUCION_DETALLE")
);

-- CreateIndex
CREATE UNIQUE INDEX "UQ_DEVOLUCION_ID_PAGO_REINTEGRO" ON "DEVOLUCION"("ID_PAGO_REINTEGRO");

-- CreateIndex
CREATE INDEX "IX_DEVOLUCION_ID_PEDIDO" ON "DEVOLUCION"("ID_PEDIDO");

-- CreateIndex
CREATE INDEX "IX_DEVOLUCION_FECHA" ON "DEVOLUCION"("FECHA");

-- CreateIndex
CREATE INDEX "IX_DEVOLUCION_DETALLE_ID_DEVOLUCION" ON "DEVOLUCION_DETALLE"("ID_DEVOLUCION");

-- CreateIndex
CREATE INDEX "IX_DEVOLUCION_DETALLE_ID_PEDIDO_DETALLE" ON "DEVOLUCION_DETALLE"("ID_PEDIDO_DETALLE");

-- AddForeignKey
ALTER TABLE "DEVOLUCION" ADD CONSTRAINT "DEVOLUCION_ID_PEDIDO_fkey" FOREIGN KEY ("ID_PEDIDO") REFERENCES "PEDIDO"("ID_PEDIDO") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "DEVOLUCION" ADD CONSTRAINT "DEVOLUCION_ID_PAGO_REINTEGRO_fkey" FOREIGN KEY ("ID_PAGO_REINTEGRO") REFERENCES "PAGO"("ID_PAGO") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "DEVOLUCION" ADD CONSTRAINT "DEVOLUCION_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID_USUARIO") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "DEVOLUCION_DETALLE" ADD CONSTRAINT "DEVOLUCION_DETALLE_ID_DEVOLUCION_fkey" FOREIGN KEY ("ID_DEVOLUCION") REFERENCES "DEVOLUCION"("ID_DEVOLUCION") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "DEVOLUCION_DETALLE" ADD CONSTRAINT "DEVOLUCION_DETALLE_ID_PEDIDO_DETALLE_fkey" FOREIGN KEY ("ID_PEDIDO_DETALLE") REFERENCES "PEDIDO_DETALLE"("ID_PEDIDO_DETALLE") ON DELETE NO ACTION ON UPDATE NO ACTION;
