-- CreateTable
CREATE TABLE "PAGO" (
    "ID_PAGO" BIGSERIAL NOT NULL,
    "ID_PEDIDO" BIGINT NOT NULL,
    "FECHA" TIMESTAMPTZ(3) NOT NULL,
    "MONTO" DECIMAL(18,2) NOT NULL,
    "MEDIO_PAGO" VARCHAR(30) NOT NULL,
    "OBSERVACIONES" VARCHAR(500),
    "ID_USUARIO" BIGINT,
    "FECHA_ALTA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ANULADO" BOOLEAN NOT NULL DEFAULT false,
    "FECHA_ANULACION" TIMESTAMPTZ(3),
    "MOTIVO_ANULACION" VARCHAR(500),
    "ID_USUARIO_ANULACION" BIGINT,

    CONSTRAINT "PAGO_pkey" PRIMARY KEY ("ID_PAGO")
);

-- CreateIndex
CREATE INDEX "IX_PAGO_ID_PEDIDO" ON "PAGO"("ID_PEDIDO");

-- CreateIndex
CREATE INDEX "IX_PAGO_FECHA" ON "PAGO"("FECHA");

-- AddForeignKey
ALTER TABLE "PAGO" ADD CONSTRAINT "PAGO_ID_PEDIDO_fkey" FOREIGN KEY ("ID_PEDIDO") REFERENCES "PEDIDO"("ID_PEDIDO") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "PAGO" ADD CONSTRAINT "PAGO_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID_USUARIO") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "PAGO" ADD CONSTRAINT "PAGO_ID_USUARIO_ANULACION_fkey" FOREIGN KEY ("ID_USUARIO_ANULACION") REFERENCES "USUARIO"("ID_USUARIO") ON DELETE NO ACTION ON UPDATE NO ACTION;

