-- CreateTable
CREATE TABLE "AUDITORIA_CAMBIO" (
    "ID_AUDITORIA_CAMBIO" BIGSERIAL NOT NULL,
    "ENTIDAD" VARCHAR(30) NOT NULL,
    "ID_ENTIDAD" BIGINT NOT NULL,
    "ACCION" VARCHAR(20) NOT NULL,
    "CAMBIOS" JSONB NOT NULL,
    "ID_USUARIO" BIGINT,
    "FECHA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AUDITORIA_CAMBIO_pkey" PRIMARY KEY ("ID_AUDITORIA_CAMBIO")
);

-- CreateIndex
CREATE INDEX "IX_AUDITORIA_CAMBIO_ENTIDAD" ON "AUDITORIA_CAMBIO"("ENTIDAD", "ID_ENTIDAD", "FECHA");

-- AddForeignKey
ALTER TABLE "AUDITORIA_CAMBIO" ADD CONSTRAINT "AUDITORIA_CAMBIO_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID_USUARIO") ON DELETE NO ACTION ON UPDATE NO ACTION;
