-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "USUARIO" (
    "ID_USUARIO" BIGSERIAL NOT NULL,
    "NOMBRE" VARCHAR(100) NOT NULL,
    "APELLIDO" VARCHAR(100) NOT NULL,
    "EMAIL" VARCHAR(150) NOT NULL,
    "USUARIO" VARCHAR(100) NOT NULL,
    "CLAVE_HASH" VARCHAR(255) NOT NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT true,
    "ES_ADMINISTRADOR" BOOLEAN NOT NULL DEFAULT false,
    "FECHA_ALTA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FECHA_MODIFICACION" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "USUARIO_pkey" PRIMARY KEY ("ID_USUARIO")
);

-- CreateTable
CREATE TABLE "CATEGORIA" (
    "ID_CATEGORIA" BIGSERIAL NOT NULL,
    "NOMBRE" VARCHAR(120) NOT NULL,
    "SLUG" VARCHAR(160) NOT NULL,
    "DESCRIPCION" VARCHAR(1000),
    "ACTIVO" BOOLEAN NOT NULL DEFAULT true,
    "FECHA_ALTA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FECHA_MODIFICACION" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "CATEGORIA_pkey" PRIMARY KEY ("ID_CATEGORIA")
);

-- CreateTable
CREATE TABLE "ITEM_CATALOGO" (
    "ID_ITEM_CATALOGO" BIGSERIAL NOT NULL,
    "ID_CATEGORIA" BIGINT NOT NULL,
    "TIPO_ITEM" VARCHAR(30) NOT NULL,
    "NOMBRE" VARCHAR(150) NOT NULL,
    "SLUG" VARCHAR(180) NOT NULL,
    "CODIGO" VARCHAR(80),
    "DESCRIPCION_CORTA" VARCHAR(300),
    "DESCRIPCION_COMPLETA" VARCHAR(4000),
    "OBSERVACIONES_INTERNAS" VARCHAR(2000),
    "PRECIO" DECIMAL(18,2),
    "COSTO" DECIMAL(18,2),
    "TIPO_MATERIAL" VARCHAR(100),
    "COLOR" VARCHAR(100),
    "IMAGEN_PRINCIPAL" VARCHAR(500),
    "STOCK_MINIMO" INTEGER NOT NULL DEFAULT 0,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT true,
    "PUBLICO" BOOLEAN NOT NULL DEFAULT false,
    "FECHA_ALTA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FECHA_MODIFICACION" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "ITEM_CATALOGO_pkey" PRIMARY KEY ("ID_ITEM_CATALOGO")
);

-- CreateTable
CREATE TABLE "ITEM_CATALOGO_IMAGEN" (
    "ID_ITEM_CATALOGO_IMAGEN" BIGSERIAL NOT NULL,
    "ID_ITEM_CATALOGO" BIGINT NOT NULL,
    "URL_IMAGEN" VARCHAR(500) NOT NULL,
    "ORDEN" INTEGER NOT NULL DEFAULT 1,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT true,
    "FECHA_ALTA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ITEM_CATALOGO_IMAGEN_pkey" PRIMARY KEY ("ID_ITEM_CATALOGO_IMAGEN")
);

-- CreateTable
CREATE TABLE "CLIENTE" (
    "ID_CLIENTE" BIGSERIAL NOT NULL,
    "NOMBRE" VARCHAR(120) NOT NULL,
    "APELLIDO" VARCHAR(120),
    "DOCUMENTO" VARCHAR(30),
    "TELEFONO" VARCHAR(50),
    "EMAIL" VARCHAR(150),
    "INSTAGRAM" VARCHAR(150),
    "DOMICILIO" VARCHAR(250),
    "LOCALIDAD" VARCHAR(120),
    "PROVINCIA" VARCHAR(120),
    "OBSERVACIONES" VARCHAR(2000),
    "FECHA_ALTA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT true,
    "FECHA_MODIFICACION" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "CLIENTE_pkey" PRIMARY KEY ("ID_CLIENTE")
);

-- CreateTable
CREATE TABLE "PEDIDO" (
    "ID_PEDIDO" BIGSERIAL NOT NULL,
    "ID_CLIENTE" BIGINT NOT NULL,
    "NUMERO_PEDIDO" VARCHAR(32),
    "ORIGEN_PEDIDO" VARCHAR(30) NOT NULL,
    "ESTADO_PEDIDO" VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    "ESTADO_COBRO" VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    "OBSERVACIONES_CLIENTE" VARCHAR(2000),
    "OBSERVACIONES_INTERNAS" VARCHAR(2000),
    "SUBTOTAL" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "TOTAL" DECIMAL(18,2) NOT NULL,
    "FECHA_ALTA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FECHA_CONFIRMACION" TIMESTAMPTZ(3),
    "FECHA_ENTREGA" TIMESTAMPTZ(3),
    "ACTIVO" BOOLEAN NOT NULL DEFAULT true,
    "FECHA_MODIFICACION" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "PEDIDO_pkey" PRIMARY KEY ("ID_PEDIDO")
);

-- CreateTable
CREATE TABLE "PEDIDO_DETALLE" (
    "ID_PEDIDO_DETALLE" BIGSERIAL NOT NULL,
    "ID_PEDIDO" BIGINT NOT NULL,
    "ID_ITEM_CATALOGO" BIGINT NOT NULL,
    "NOMBRE_ITEM_SNAPSHOT" VARCHAR(150) NOT NULL,
    "CANTIDAD" DECIMAL(18,3) NOT NULL,
    "PRECIO_UNITARIO" DECIMAL(18,2) NOT NULL,
    "COSTO_UNITARIO" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "SUBTOTAL" DECIMAL(18,2) NOT NULL,
    "FECHA_ALTA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FECHA_MODIFICACION" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "PEDIDO_DETALLE_pkey" PRIMARY KEY ("ID_PEDIDO_DETALLE")
);

-- CreateTable
CREATE TABLE "SOLICITUD_ESPECIAL" (
    "ID_SOLICITUD_ESPECIAL" BIGSERIAL NOT NULL,
    "ID_CLIENTE" BIGINT,
    "NOMBRE_SOLICITANTE" VARCHAR(150) NOT NULL,
    "TELEFONO" VARCHAR(50),
    "EMAIL" VARCHAR(150),
    "DESCRIPCION" VARCHAR(4000) NOT NULL,
    "ESTADO_SOLICITUD" VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    "OBSERVACIONES" VARCHAR(2000),
    "FECHA_ALTA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FECHA_MODIFICACION" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "SOLICITUD_ESPECIAL_pkey" PRIMARY KEY ("ID_SOLICITUD_ESPECIAL")
);

-- CreateTable
CREATE TABLE "ESTADO_STOCK" (
    "ID_ESTADO_STOCK" BIGSERIAL NOT NULL,
    "ID_ITEM_CATALOGO" BIGINT NOT NULL,
    "ID_USUARIO" BIGINT,
    "TIPO_STOCK" VARCHAR(30) NOT NULL,
    "STOCK_ACTUAL" DECIMAL(18,3) NOT NULL,
    "STOCK_ANTERIOR" DECIMAL(18,3) NOT NULL,
    "TIPO_MOVIMIENTO" VARCHAR(40) NOT NULL,
    "CANTIDAD_MOVIMIENTO" DECIMAL(18,3) NOT NULL,
    "ORIGEN_MOVIMIENTO" VARCHAR(30) NOT NULL,
    "ID_REFERENCIA_ORIGEN" BIGINT,
    "ID_REFERENCIA_DETALLE" BIGINT,
    "OBSERVACIONES" VARCHAR(2000),
    "FECHA_ALTA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ESTADO_STOCK_pkey" PRIMARY KEY ("ID_ESTADO_STOCK")
);

-- CreateTable
CREATE TABLE "ORDEN_PRODUCCION" (
    "ID_ORDEN_PRODUCCION" BIGSERIAL NOT NULL,
    "ESTADO_PRODUCCION" VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    "OBSERVACIONES" VARCHAR(2000),
    "FECHA_ALTA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FECHA_INICIO" TIMESTAMPTZ(3),
    "FECHA_FIN" TIMESTAMPTZ(3),
    "ACTIVO" BOOLEAN NOT NULL DEFAULT true,
    "FECHA_MODIFICACION" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "ORDEN_PRODUCCION_pkey" PRIMARY KEY ("ID_ORDEN_PRODUCCION")
);

-- CreateTable
CREATE TABLE "ORDEN_PRODUCCION_DETALLE" (
    "ID_ORDEN_PRODUCCION_DETALLE" BIGSERIAL NOT NULL,
    "ID_ORDEN_PRODUCCION" BIGINT NOT NULL,
    "ID_ITEM_CATALOGO_PRODUCTO" BIGINT NOT NULL,
    "CANTIDAD" DECIMAL(18,3) NOT NULL,
    "OBSERVACIONES" VARCHAR(2000),
    "FECHA_ALTA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FECHA_MODIFICACION" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "ORDEN_PRODUCCION_DETALLE_pkey" PRIMARY KEY ("ID_ORDEN_PRODUCCION_DETALLE")
);

-- CreateTable
CREATE TABLE "ORDEN_PRODUCCION_CONSUMO" (
    "ID_ORDEN_PRODUCCION_CONSUMO" BIGSERIAL NOT NULL,
    "ID_ORDEN_PRODUCCION" BIGINT NOT NULL,
    "ID_ITEM_CATALOGO_INSUMO" BIGINT NOT NULL,
    "CANTIDAD" DECIMAL(18,4) NOT NULL,
    "FECHA_ALTA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ORDEN_PRODUCCION_CONSUMO_pkey" PRIMARY KEY ("ID_ORDEN_PRODUCCION_CONSUMO")
);

-- CreateTable
CREATE TABLE "ITEM_CATALOGO_COMPONENTE" (
    "ID_ITEM_CATALOGO_COMPONENTE" BIGSERIAL NOT NULL,
    "ID_ITEM_CATALOGO_PADRE" BIGINT NOT NULL,
    "ID_ITEM_CATALOGO_HIJO" BIGINT NOT NULL,
    "CANTIDAD_REQUERIDA" DECIMAL(18,3) NOT NULL,
    "UNIDAD_MEDIDA" VARCHAR(30) NOT NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT true,
    "FECHA_ALTA" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FECHA_MODIFICACION" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "ITEM_CATALOGO_COMPONENTE_pkey" PRIMARY KEY ("ID_ITEM_CATALOGO_COMPONENTE")
);

-- CreateIndex
CREATE UNIQUE INDEX "UQ_USUARIO_EMAIL" ON "USUARIO"("EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "UQ_USUARIO_USUARIO" ON "USUARIO"("USUARIO");

-- CreateIndex
CREATE UNIQUE INDEX "UQ_CATEGORIA_SLUG" ON "CATEGORIA"("SLUG");

-- CreateIndex
CREATE INDEX "IX_ITEM_CATALOGO_ID_CATEGORIA" ON "ITEM_CATALOGO"("ID_CATEGORIA");

-- CreateIndex
CREATE INDEX "IX_ITEM_CATALOGO_TIPO_ITEM" ON "ITEM_CATALOGO"("TIPO_ITEM");

-- CreateIndex
CREATE UNIQUE INDEX "UQ_ITEM_CATALOGO_SLUG" ON "ITEM_CATALOGO"("SLUG");

-- CreateIndex
CREATE INDEX "IX_ITEM_CATALOGO_IMAGEN_ID_ITEM_CATALOGO" ON "ITEM_CATALOGO_IMAGEN"("ID_ITEM_CATALOGO");

-- CreateIndex
CREATE INDEX "IX_CLIENTE_TELEFONO" ON "CLIENTE"("TELEFONO");

-- CreateIndex
CREATE INDEX "IX_CLIENTE_INSTAGRAM" ON "CLIENTE"("INSTAGRAM");

-- CreateIndex
CREATE INDEX "IX_PEDIDO_ID_CLIENTE" ON "PEDIDO"("ID_CLIENTE");

-- CreateIndex
CREATE INDEX "IX_PEDIDO_NUMERO_PEDIDO" ON "PEDIDO"("NUMERO_PEDIDO");

-- CreateIndex
CREATE INDEX "IX_PEDIDO_ESTADO_PEDIDO" ON "PEDIDO"("ESTADO_PEDIDO");

-- CreateIndex
CREATE INDEX "IX_PEDIDO_ESTADO_COBRO" ON "PEDIDO"("ESTADO_COBRO");

-- CreateIndex
CREATE INDEX "IX_PEDIDO_FECHA_ALTA" ON "PEDIDO"("FECHA_ALTA");

-- CreateIndex
CREATE INDEX "IX_PEDIDO_DETALLE_ID_PEDIDO" ON "PEDIDO_DETALLE"("ID_PEDIDO");

-- CreateIndex
CREATE INDEX "IX_PEDIDO_DETALLE_ID_ITEM_CATALOGO" ON "PEDIDO_DETALLE"("ID_ITEM_CATALOGO");

-- CreateIndex
CREATE INDEX "IX_SOLICITUD_ESPECIAL_ID_CLIENTE" ON "SOLICITUD_ESPECIAL"("ID_CLIENTE");

-- CreateIndex
CREATE INDEX "IX_SOLICITUD_ESPECIAL_ESTADO_SOLICITUD" ON "SOLICITUD_ESPECIAL"("ESTADO_SOLICITUD");

-- CreateIndex
CREATE INDEX "IX_ESTADO_STOCK_ID_ITEM_CATALOGO" ON "ESTADO_STOCK"("ID_ITEM_CATALOGO");

-- CreateIndex
CREATE INDEX "IX_ESTADO_STOCK_ID_USUARIO" ON "ESTADO_STOCK"("ID_USUARIO");

-- CreateIndex
CREATE INDEX "IX_ESTADO_STOCK_TIPO_STOCK" ON "ESTADO_STOCK"("TIPO_STOCK");

-- CreateIndex
CREATE INDEX "IX_ESTADO_STOCK_TIPO_MOVIMIENTO" ON "ESTADO_STOCK"("TIPO_MOVIMIENTO");

-- CreateIndex
CREATE INDEX "IX_ESTADO_STOCK_IDEMPOTENCIA" ON "ESTADO_STOCK"("ORIGEN_MOVIMIENTO", "ID_REFERENCIA_ORIGEN", "ID_REFERENCIA_DETALLE", "ID_ITEM_CATALOGO", "TIPO_MOVIMIENTO");

-- CreateIndex
CREATE INDEX "IX_ORDEN_PRODUCCION_ESTADO_PRODUCCION" ON "ORDEN_PRODUCCION"("ESTADO_PRODUCCION");

-- CreateIndex
CREATE INDEX "IX_ORDEN_PRODUCCION_DETALLE_ID_ORDEN_PRODUCCION" ON "ORDEN_PRODUCCION_DETALLE"("ID_ORDEN_PRODUCCION");

-- CreateIndex
CREATE INDEX "IX_ORDEN_PRODUCCION_DETALLE_ID_ITEM_CATALOGO_PRODUCTO" ON "ORDEN_PRODUCCION_DETALLE"("ID_ITEM_CATALOGO_PRODUCTO");

-- CreateIndex
CREATE INDEX "IX_ORDEN_PRODUCCION_CONSUMO_ID_ORDEN_PRODUCCION" ON "ORDEN_PRODUCCION_CONSUMO"("ID_ORDEN_PRODUCCION");

-- CreateIndex
CREATE INDEX "IX_ORDEN_PRODUCCION_CONSUMO_ID_ITEM_CATALOGO_INSUMO" ON "ORDEN_PRODUCCION_CONSUMO"("ID_ITEM_CATALOGO_INSUMO");

-- CreateIndex
CREATE INDEX "IX_ITEM_CATALOGO_COMPONENTE_ID_ITEM_CATALOGO_PADRE" ON "ITEM_CATALOGO_COMPONENTE"("ID_ITEM_CATALOGO_PADRE");

-- CreateIndex
CREATE INDEX "IX_ITEM_CATALOGO_COMPONENTE_ID_ITEM_CATALOGO_HIJO" ON "ITEM_CATALOGO_COMPONENTE"("ID_ITEM_CATALOGO_HIJO");

-- CreateIndex
CREATE UNIQUE INDEX "UQ_ITEM_CATALOGO_COMPONENTE_PADRE_HIJO" ON "ITEM_CATALOGO_COMPONENTE"("ID_ITEM_CATALOGO_PADRE", "ID_ITEM_CATALOGO_HIJO");

-- AddForeignKey
ALTER TABLE "ITEM_CATALOGO" ADD CONSTRAINT "ITEM_CATALOGO_ID_CATEGORIA_fkey" FOREIGN KEY ("ID_CATEGORIA") REFERENCES "CATEGORIA"("ID_CATEGORIA") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ITEM_CATALOGO_IMAGEN" ADD CONSTRAINT "ITEM_CATALOGO_IMAGEN_ID_ITEM_CATALOGO_fkey" FOREIGN KEY ("ID_ITEM_CATALOGO") REFERENCES "ITEM_CATALOGO"("ID_ITEM_CATALOGO") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "PEDIDO" ADD CONSTRAINT "PEDIDO_ID_CLIENTE_fkey" FOREIGN KEY ("ID_CLIENTE") REFERENCES "CLIENTE"("ID_CLIENTE") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "PEDIDO_DETALLE" ADD CONSTRAINT "PEDIDO_DETALLE_ID_PEDIDO_fkey" FOREIGN KEY ("ID_PEDIDO") REFERENCES "PEDIDO"("ID_PEDIDO") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "PEDIDO_DETALLE" ADD CONSTRAINT "PEDIDO_DETALLE_ID_ITEM_CATALOGO_fkey" FOREIGN KEY ("ID_ITEM_CATALOGO") REFERENCES "ITEM_CATALOGO"("ID_ITEM_CATALOGO") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "SOLICITUD_ESPECIAL" ADD CONSTRAINT "SOLICITUD_ESPECIAL_ID_CLIENTE_fkey" FOREIGN KEY ("ID_CLIENTE") REFERENCES "CLIENTE"("ID_CLIENTE") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ESTADO_STOCK" ADD CONSTRAINT "ESTADO_STOCK_ID_ITEM_CATALOGO_fkey" FOREIGN KEY ("ID_ITEM_CATALOGO") REFERENCES "ITEM_CATALOGO"("ID_ITEM_CATALOGO") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ESTADO_STOCK" ADD CONSTRAINT "ESTADO_STOCK_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID_USUARIO") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ORDEN_PRODUCCION_DETALLE" ADD CONSTRAINT "ORDEN_PRODUCCION_DETALLE_ID_ORDEN_PRODUCCION_fkey" FOREIGN KEY ("ID_ORDEN_PRODUCCION") REFERENCES "ORDEN_PRODUCCION"("ID_ORDEN_PRODUCCION") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ORDEN_PRODUCCION_DETALLE" ADD CONSTRAINT "ORDEN_PRODUCCION_DETALLE_ID_ITEM_CATALOGO_PRODUCTO_fkey" FOREIGN KEY ("ID_ITEM_CATALOGO_PRODUCTO") REFERENCES "ITEM_CATALOGO"("ID_ITEM_CATALOGO") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ORDEN_PRODUCCION_CONSUMO" ADD CONSTRAINT "ORDEN_PRODUCCION_CONSUMO_ID_ORDEN_PRODUCCION_fkey" FOREIGN KEY ("ID_ORDEN_PRODUCCION") REFERENCES "ORDEN_PRODUCCION"("ID_ORDEN_PRODUCCION") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ORDEN_PRODUCCION_CONSUMO" ADD CONSTRAINT "ORDEN_PRODUCCION_CONSUMO_ID_ITEM_CATALOGO_INSUMO_fkey" FOREIGN KEY ("ID_ITEM_CATALOGO_INSUMO") REFERENCES "ITEM_CATALOGO"("ID_ITEM_CATALOGO") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ITEM_CATALOGO_COMPONENTE" ADD CONSTRAINT "ITEM_CATALOGO_COMPONENTE_ID_ITEM_CATALOGO_PADRE_fkey" FOREIGN KEY ("ID_ITEM_CATALOGO_PADRE") REFERENCES "ITEM_CATALOGO"("ID_ITEM_CATALOGO") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ITEM_CATALOGO_COMPONENTE" ADD CONSTRAINT "ITEM_CATALOGO_COMPONENTE_ID_ITEM_CATALOGO_HIJO_fkey" FOREIGN KEY ("ID_ITEM_CATALOGO_HIJO") REFERENCES "ITEM_CATALOGO"("ID_ITEM_CATALOGO") ON DELETE NO ACTION ON UPDATE NO ACTION;


-- Unicidad sin distinguir mayusculas (SQL crudo: Prisma no modela indices por expresion).
-- SQL Server comparaba usuario/email con collation CI; en PostgreSQL esto evita que convivan
-- "Admin" y "admin" aunque lleguen dos altas concurrentes.
CREATE UNIQUE INDEX "UQ_USUARIO_EMAIL_LOWER" ON "USUARIO"(LOWER("EMAIL"));

-- CreateIndex
CREATE UNIQUE INDEX "UQ_USUARIO_USUARIO_LOWER" ON "USUARIO"(LOWER("USUARIO"));
