BEGIN TRY

BEGIN TRAN;

-- Add columns to ITEM_CATALOGO
ALTER TABLE [dbo].[ITEM_CATALOGO]
ADD [STOCK_MINIMO] INT NOT NULL CONSTRAINT [ITEM_CATALOGO_STOCK_MINIMO_df] DEFAULT 0;

-- Add columns to PEDIDO
ALTER TABLE [dbo].[PEDIDO]
ADD [NUMERO_PEDIDO] VARCHAR(32) NULL,
    [SUBTOTAL] DECIMAL(18,2) NOT NULL CONSTRAINT [PEDIDO_SUBTOTAL_df] DEFAULT 0;

-- Add column to PEDIDO_DETALLE
ALTER TABLE [dbo].[PEDIDO_DETALLE]
ADD [COSTO_UNITARIO] DECIMAL(18,2) NOT NULL CONSTRAINT [PEDIDO_DETALLE_COSTO_UNITARIO_df] DEFAULT 0;

-- Add column to ESTADO_STOCK
ALTER TABLE [dbo].[ESTADO_STOCK]
ADD [ID_USUARIO] BIGINT NULL;

-- Rename ITEM_CATALOGO_COMPONENTE child column without colliding with PK
EXEC sp_rename
    N'[dbo].[ITEM_CATALOGO_COMPONENTE].[ID_ITEM_CATALOGO_COMPONENTE_HIJO]',
    N'ID_ITEM_CATALOGO_HIJO',
    N'COLUMN';

-- Rename related index
EXEC sp_rename
    N'[dbo].[ITEM_CATALOGO_COMPONENTE].[IX_ITEM_CATALOGO_COMPONENTE_ID_ITEM_CATALOGO_COMPONENTE_HIJO]',
    N'IX_ITEM_CATALOGO_COMPONENTE_ID_ITEM_CATALOGO_HIJO',
    N'INDEX';

-- Drop and recreate related unique constraint
ALTER TABLE [dbo].[ITEM_CATALOGO_COMPONENTE]
DROP CONSTRAINT [UQ_ITEM_CATALOGO_COMPONENTE_PADRE_HIJO];

ALTER TABLE [dbo].[ITEM_CATALOGO_COMPONENTE]
ADD CONSTRAINT [UQ_ITEM_CATALOGO_COMPONENTE_PADRE_HIJO]
UNIQUE NONCLUSTERED ([ID_ITEM_CATALOGO_PADRE], [ID_ITEM_CATALOGO_HIJO]);

-- Drop and recreate FK to renamed child column
ALTER TABLE [dbo].[ITEM_CATALOGO_COMPONENTE]
DROP CONSTRAINT [ITEM_CATALOGO_COMPONENTE_ID_ITEM_CATALOGO_COMPONENTE_HIJO_fkey];

ALTER TABLE [dbo].[ITEM_CATALOGO_COMPONENTE]
ADD CONSTRAINT [ITEM_CATALOGO_COMPONENTE_ID_ITEM_CATALOGO_HIJO_fkey]
FOREIGN KEY ([ID_ITEM_CATALOGO_HIJO]) REFERENCES [dbo].[ITEM_CATALOGO]([ID_ITEM_CATALOGO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Create table ORDEN_PRODUCCION_CONSUMO
CREATE TABLE [dbo].[ORDEN_PRODUCCION_CONSUMO] (
    [ID_ORDEN_PRODUCCION_CONSUMO] BIGINT NOT NULL IDENTITY(1,1),
    [ID_ORDEN_PRODUCCION] BIGINT NOT NULL,
    [ID_ITEM_CATALOGO_INSUMO] BIGINT NOT NULL,
    [CANTIDAD] DECIMAL(18,4) NOT NULL,
    [FECHA_ALTA] DATETIME2 NOT NULL CONSTRAINT [ORDEN_PRODUCCION_CONSUMO_FECHA_ALTA_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [ORDEN_PRODUCCION_CONSUMO_pkey] PRIMARY KEY CLUSTERED ([ID_ORDEN_PRODUCCION_CONSUMO])
);

CREATE NONCLUSTERED INDEX [IX_PEDIDO_NUMERO_PEDIDO] ON [dbo].[PEDIDO]([NUMERO_PEDIDO]);
CREATE NONCLUSTERED INDEX [IX_ESTADO_STOCK_ID_USUARIO] ON [dbo].[ESTADO_STOCK]([ID_USUARIO]);
CREATE NONCLUSTERED INDEX [IX_ORDEN_PRODUCCION_CONSUMO_ID_ORDEN_PRODUCCION] ON [dbo].[ORDEN_PRODUCCION_CONSUMO]([ID_ORDEN_PRODUCCION]);
CREATE NONCLUSTERED INDEX [IX_ORDEN_PRODUCCION_CONSUMO_ID_ITEM_CATALOGO_INSUMO] ON [dbo].[ORDEN_PRODUCCION_CONSUMO]([ID_ITEM_CATALOGO_INSUMO]);

ALTER TABLE [dbo].[ESTADO_STOCK]
ADD CONSTRAINT [ESTADO_STOCK_ID_USUARIO_fkey]
FOREIGN KEY ([ID_USUARIO]) REFERENCES [dbo].[USUARIO]([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE [dbo].[ORDEN_PRODUCCION_CONSUMO]
ADD CONSTRAINT [ORDEN_PRODUCCION_CONSUMO_ID_ORDEN_PRODUCCION_fkey]
FOREIGN KEY ([ID_ORDEN_PRODUCCION]) REFERENCES [dbo].[ORDEN_PRODUCCION]([ID_ORDEN_PRODUCCION]) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE [dbo].[ORDEN_PRODUCCION_CONSUMO]
ADD CONSTRAINT [ORDEN_PRODUCCION_CONSUMO_ID_ITEM_CATALOGO_INSUMO_fkey]
FOREIGN KEY ([ID_ITEM_CATALOGO_INSUMO]) REFERENCES [dbo].[ITEM_CATALOGO]([ID_ITEM_CATALOGO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
