/*
  Warnings:

  - You are about to drop the `Healthcheck` table. If the table is not empty, all the data it contains will be lost.

*/
BEGIN TRY

BEGIN TRAN;

-- DropTable
DROP TABLE [dbo].[Healthcheck];

-- CreateTable
CREATE TABLE [dbo].[USUARIO] (
    [ID_USUARIO] BIGINT NOT NULL IDENTITY(1,1),
    [NOMBRE] NVARCHAR(100) NOT NULL,
    [APELLIDO] NVARCHAR(100) NOT NULL,
    [EMAIL] VARCHAR(150) NOT NULL,
    [USUARIO] VARCHAR(100) NOT NULL,
    [CLAVE_HASH] VARCHAR(255) NOT NULL,
    [ACTIVO] BIT NOT NULL CONSTRAINT [USUARIO_ACTIVO_df] DEFAULT 1,
    [FECHA_ALTA] DATETIME2 NOT NULL CONSTRAINT [USUARIO_FECHA_ALTA_df] DEFAULT CURRENT_TIMESTAMP,
    [FECHA_MODIFICACION] DATETIME2 NOT NULL,
    CONSTRAINT [USUARIO_pkey] PRIMARY KEY CLUSTERED ([ID_USUARIO]),
    CONSTRAINT [UQ_USUARIO_EMAIL] UNIQUE NONCLUSTERED ([EMAIL]),
    CONSTRAINT [UQ_USUARIO_USUARIO] UNIQUE NONCLUSTERED ([USUARIO])
);

-- CreateTable
CREATE TABLE [dbo].[CATEGORIA] (
    [ID_CATEGORIA] BIGINT NOT NULL IDENTITY(1,1),
    [NOMBRE] NVARCHAR(120) NOT NULL,
    [SLUG] VARCHAR(160) NOT NULL,
    [DESCRIPCION] NVARCHAR(1000),
    [ACTIVO] BIT NOT NULL CONSTRAINT [CATEGORIA_ACTIVO_df] DEFAULT 1,
    [FECHA_ALTA] DATETIME2 NOT NULL CONSTRAINT [CATEGORIA_FECHA_ALTA_df] DEFAULT CURRENT_TIMESTAMP,
    [FECHA_MODIFICACION] DATETIME2 NOT NULL,
    CONSTRAINT [CATEGORIA_pkey] PRIMARY KEY CLUSTERED ([ID_CATEGORIA]),
    CONSTRAINT [UQ_CATEGORIA_SLUG] UNIQUE NONCLUSTERED ([SLUG])
);

-- CreateTable
CREATE TABLE [dbo].[ITEM_CATALOGO] (
    [ID_ITEM_CATALOGO] BIGINT NOT NULL IDENTITY(1,1),
    [ID_CATEGORIA] BIGINT NOT NULL,
    [TIPO_ITEM] VARCHAR(30) NOT NULL,
    [NOMBRE] NVARCHAR(150) NOT NULL,
    [SLUG] VARCHAR(180) NOT NULL,
    [CODIGO] VARCHAR(80),
    [DESCRIPCION_CORTA] NVARCHAR(300),
    [DESCRIPCION_COMPLETA] NVARCHAR(4000),
    [OBSERVACIONES_INTERNAS] NVARCHAR(2000),
    [PRECIO] DECIMAL(18,2),
    [COSTO] DECIMAL(18,2),
    [TIPO_MATERIAL] NVARCHAR(100),
    [COLOR] NVARCHAR(100),
    [IMAGEN_PRINCIPAL] VARCHAR(500),
    [ACTIVO] BIT NOT NULL CONSTRAINT [ITEM_CATALOGO_ACTIVO_df] DEFAULT 1,
    [PUBLICO] BIT NOT NULL CONSTRAINT [ITEM_CATALOGO_PUBLICO_df] DEFAULT 0,
    [FECHA_ALTA] DATETIME2 NOT NULL CONSTRAINT [ITEM_CATALOGO_FECHA_ALTA_df] DEFAULT CURRENT_TIMESTAMP,
    [FECHA_MODIFICACION] DATETIME2 NOT NULL,
    CONSTRAINT [ITEM_CATALOGO_pkey] PRIMARY KEY CLUSTERED ([ID_ITEM_CATALOGO]),
    CONSTRAINT [UQ_ITEM_CATALOGO_SLUG] UNIQUE NONCLUSTERED ([SLUG])
);

-- CreateTable
CREATE TABLE [dbo].[ITEM_CATALOGO_IMAGEN] (
    [ID_ITEM_CATALOGO_IMAGEN] BIGINT NOT NULL IDENTITY(1,1),
    [ID_ITEM_CATALOGO] BIGINT NOT NULL,
    [URL_IMAGEN] VARCHAR(500) NOT NULL,
    [ORDEN] INT NOT NULL CONSTRAINT [ITEM_CATALOGO_IMAGEN_ORDEN_df] DEFAULT 1,
    [ACTIVO] BIT NOT NULL CONSTRAINT [ITEM_CATALOGO_IMAGEN_ACTIVO_df] DEFAULT 1,
    [FECHA_ALTA] DATETIME2 NOT NULL CONSTRAINT [ITEM_CATALOGO_IMAGEN_FECHA_ALTA_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [ITEM_CATALOGO_IMAGEN_pkey] PRIMARY KEY CLUSTERED ([ID_ITEM_CATALOGO_IMAGEN])
);

-- CreateTable
CREATE TABLE [dbo].[CLIENTE] (
    [ID_CLIENTE] BIGINT NOT NULL IDENTITY(1,1),
    [NOMBRE] NVARCHAR(120) NOT NULL,
    [APELLIDO] NVARCHAR(120),
    [DOCUMENTO] VARCHAR(30),
    [TELEFONO] VARCHAR(50),
    [EMAIL] VARCHAR(150),
    [INSTAGRAM] VARCHAR(150),
    [DOMICILIO] NVARCHAR(250),
    [LOCALIDAD] NVARCHAR(120),
    [PROVINCIA] NVARCHAR(120),
    [OBSERVACIONES] NVARCHAR(2000),
    [FECHA_ALTA] DATETIME2 NOT NULL CONSTRAINT [CLIENTE_FECHA_ALTA_df] DEFAULT CURRENT_TIMESTAMP,
    [ACTIVO] BIT NOT NULL CONSTRAINT [CLIENTE_ACTIVO_df] DEFAULT 1,
    [FECHA_MODIFICACION] DATETIME2 NOT NULL,
    CONSTRAINT [CLIENTE_pkey] PRIMARY KEY CLUSTERED ([ID_CLIENTE])
);

-- CreateTable
CREATE TABLE [dbo].[PEDIDO] (
    [ID_PEDIDO] BIGINT NOT NULL IDENTITY(1,1),
    [ID_CLIENTE] BIGINT NOT NULL,
    [ORIGEN_PEDIDO] VARCHAR(30) NOT NULL,
    [ESTADO_PEDIDO] VARCHAR(30) NOT NULL CONSTRAINT [PEDIDO_ESTADO_PEDIDO_df] DEFAULT 'PENDIENTE',
    [ESTADO_COBRO] VARCHAR(30) NOT NULL CONSTRAINT [PEDIDO_ESTADO_COBRO_df] DEFAULT 'PENDIENTE',
    [OBSERVACIONES_CLIENTE] NVARCHAR(2000),
    [OBSERVACIONES_INTERNAS] NVARCHAR(2000),
    [TOTAL] DECIMAL(18,2) NOT NULL,
    [FECHA_ALTA] DATETIME2 NOT NULL CONSTRAINT [PEDIDO_FECHA_ALTA_df] DEFAULT CURRENT_TIMESTAMP,
    [FECHA_CONFIRMACION] DATETIME2,
    [FECHA_ENTREGA] DATETIME2,
    [ACTIVO] BIT NOT NULL CONSTRAINT [PEDIDO_ACTIVO_df] DEFAULT 1,
    [FECHA_MODIFICACION] DATETIME2 NOT NULL,
    CONSTRAINT [PEDIDO_pkey] PRIMARY KEY CLUSTERED ([ID_PEDIDO])
);

-- CreateTable
CREATE TABLE [dbo].[PEDIDO_DETALLE] (
    [ID_PEDIDO_DETALLE] BIGINT NOT NULL IDENTITY(1,1),
    [ID_PEDIDO] BIGINT NOT NULL,
    [ID_ITEM_CATALOGO] BIGINT NOT NULL,
    [NOMBRE_ITEM_SNAPSHOT] NVARCHAR(150) NOT NULL,
    [CANTIDAD] DECIMAL(18,3) NOT NULL,
    [PRECIO_UNITARIO] DECIMAL(18,2) NOT NULL,
    [SUBTOTAL] DECIMAL(18,2) NOT NULL,
    [FECHA_ALTA] DATETIME2 NOT NULL CONSTRAINT [PEDIDO_DETALLE_FECHA_ALTA_df] DEFAULT CURRENT_TIMESTAMP,
    [FECHA_MODIFICACION] DATETIME2 NOT NULL,
    CONSTRAINT [PEDIDO_DETALLE_pkey] PRIMARY KEY CLUSTERED ([ID_PEDIDO_DETALLE])
);

-- CreateTable
CREATE TABLE [dbo].[SOLICITUD_ESPECIAL] (
    [ID_SOLICITUD_ESPECIAL] BIGINT NOT NULL IDENTITY(1,1),
    [ID_CLIENTE] BIGINT,
    [NOMBRE_SOLICITANTE] NVARCHAR(150) NOT NULL,
    [TELEFONO] VARCHAR(50),
    [EMAIL] VARCHAR(150),
    [DESCRIPCION] NVARCHAR(4000) NOT NULL,
    [ESTADO_SOLICITUD] VARCHAR(30) NOT NULL CONSTRAINT [SOLICITUD_ESPECIAL_ESTADO_SOLICITUD_df] DEFAULT 'PENDIENTE',
    [OBSERVACIONES] NVARCHAR(2000),
    [FECHA_ALTA] DATETIME2 NOT NULL CONSTRAINT [SOLICITUD_ESPECIAL_FECHA_ALTA_df] DEFAULT CURRENT_TIMESTAMP,
    [FECHA_MODIFICACION] DATETIME2 NOT NULL,
    CONSTRAINT [SOLICITUD_ESPECIAL_pkey] PRIMARY KEY CLUSTERED ([ID_SOLICITUD_ESPECIAL])
);

-- CreateTable
CREATE TABLE [dbo].[ESTADO_STOCK] (
    [ID_ESTADO_STOCK] BIGINT NOT NULL IDENTITY(1,1),
    [ID_ITEM_CATALOGO] BIGINT NOT NULL,
    [TIPO_STOCK] VARCHAR(30) NOT NULL,
    [STOCK_ACTUAL] DECIMAL(18,3) NOT NULL,
    [STOCK_ANTERIOR] DECIMAL(18,3) NOT NULL,
    [TIPO_MOVIMIENTO] VARCHAR(40) NOT NULL,
    [CANTIDAD_MOVIMIENTO] DECIMAL(18,3) NOT NULL,
    [ORIGEN_MOVIMIENTO] VARCHAR(30) NOT NULL,
    [ID_REFERENCIA_ORIGEN] BIGINT,
    [OBSERVACIONES] NVARCHAR(2000),
    [FECHA_ALTA] DATETIME2 NOT NULL CONSTRAINT [ESTADO_STOCK_FECHA_ALTA_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [ESTADO_STOCK_pkey] PRIMARY KEY CLUSTERED ([ID_ESTADO_STOCK])
);

-- CreateTable
CREATE TABLE [dbo].[ORDEN_PRODUCCION] (
    [ID_ORDEN_PRODUCCION] BIGINT NOT NULL IDENTITY(1,1),
    [ESTADO_PRODUCCION] VARCHAR(30) NOT NULL CONSTRAINT [ORDEN_PRODUCCION_ESTADO_PRODUCCION_df] DEFAULT 'PENDIENTE',
    [OBSERVACIONES] NVARCHAR(2000),
    [FECHA_ALTA] DATETIME2 NOT NULL CONSTRAINT [ORDEN_PRODUCCION_FECHA_ALTA_df] DEFAULT CURRENT_TIMESTAMP,
    [FECHA_INICIO] DATETIME2,
    [FECHA_FIN] DATETIME2,
    [ACTIVO] BIT NOT NULL CONSTRAINT [ORDEN_PRODUCCION_ACTIVO_df] DEFAULT 1,
    [FECHA_MODIFICACION] DATETIME2 NOT NULL,
    CONSTRAINT [ORDEN_PRODUCCION_pkey] PRIMARY KEY CLUSTERED ([ID_ORDEN_PRODUCCION])
);

-- CreateTable
CREATE TABLE [dbo].[ORDEN_PRODUCCION_DETALLE] (
    [ID_ORDEN_PRODUCCION_DETALLE] BIGINT NOT NULL IDENTITY(1,1),
    [ID_ORDEN_PRODUCCION] BIGINT NOT NULL,
    [ID_ITEM_CATALOGO_PRODUCTO] BIGINT NOT NULL,
    [CANTIDAD] DECIMAL(18,3) NOT NULL,
    [OBSERVACIONES] NVARCHAR(2000),
    [FECHA_ALTA] DATETIME2 NOT NULL CONSTRAINT [ORDEN_PRODUCCION_DETALLE_FECHA_ALTA_df] DEFAULT CURRENT_TIMESTAMP,
    [FECHA_MODIFICACION] DATETIME2 NOT NULL,
    CONSTRAINT [ORDEN_PRODUCCION_DETALLE_pkey] PRIMARY KEY CLUSTERED ([ID_ORDEN_PRODUCCION_DETALLE])
);

-- CreateTable
CREATE TABLE [dbo].[ITEM_CATALOGO_COMPONENTE] (
    [ID_ITEM_CATALOGO_COMPONENTE] BIGINT NOT NULL IDENTITY(1,1),
    [ID_ITEM_CATALOGO_PADRE] BIGINT NOT NULL,
    [ID_ITEM_CATALOGO_COMPONENTE_HIJO] BIGINT NOT NULL,
    [CANTIDAD_REQUERIDA] DECIMAL(18,3) NOT NULL,
    [UNIDAD_MEDIDA] VARCHAR(30) NOT NULL,
    [ACTIVO] BIT NOT NULL CONSTRAINT [ITEM_CATALOGO_COMPONENTE_ACTIVO_df] DEFAULT 1,
    [FECHA_ALTA] DATETIME2 NOT NULL CONSTRAINT [ITEM_CATALOGO_COMPONENTE_FECHA_ALTA_df] DEFAULT CURRENT_TIMESTAMP,
    [FECHA_MODIFICACION] DATETIME2 NOT NULL,
    CONSTRAINT [ITEM_CATALOGO_COMPONENTE_pkey] PRIMARY KEY CLUSTERED ([ID_ITEM_CATALOGO_COMPONENTE]),
    CONSTRAINT [UQ_ITEM_CATALOGO_COMPONENTE_PADRE_HIJO] UNIQUE NONCLUSTERED ([ID_ITEM_CATALOGO_PADRE],[ID_ITEM_CATALOGO_COMPONENTE_HIJO])
);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_ITEM_CATALOGO_ID_CATEGORIA] ON [dbo].[ITEM_CATALOGO]([ID_CATEGORIA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_ITEM_CATALOGO_TIPO_ITEM] ON [dbo].[ITEM_CATALOGO]([TIPO_ITEM]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_ITEM_CATALOGO_IMAGEN_ID_ITEM_CATALOGO] ON [dbo].[ITEM_CATALOGO_IMAGEN]([ID_ITEM_CATALOGO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_CLIENTE_TELEFONO] ON [dbo].[CLIENTE]([TELEFONO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_CLIENTE_INSTAGRAM] ON [dbo].[CLIENTE]([INSTAGRAM]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_PEDIDO_ID_CLIENTE] ON [dbo].[PEDIDO]([ID_CLIENTE]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_PEDIDO_ESTADO_PEDIDO] ON [dbo].[PEDIDO]([ESTADO_PEDIDO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_PEDIDO_ESTADO_COBRO] ON [dbo].[PEDIDO]([ESTADO_COBRO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_PEDIDO_FECHA_ALTA] ON [dbo].[PEDIDO]([FECHA_ALTA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_PEDIDO_DETALLE_ID_PEDIDO] ON [dbo].[PEDIDO_DETALLE]([ID_PEDIDO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_PEDIDO_DETALLE_ID_ITEM_CATALOGO] ON [dbo].[PEDIDO_DETALLE]([ID_ITEM_CATALOGO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_SOLICITUD_ESPECIAL_ID_CLIENTE] ON [dbo].[SOLICITUD_ESPECIAL]([ID_CLIENTE]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_SOLICITUD_ESPECIAL_ESTADO_SOLICITUD] ON [dbo].[SOLICITUD_ESPECIAL]([ESTADO_SOLICITUD]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_ESTADO_STOCK_ID_ITEM_CATALOGO] ON [dbo].[ESTADO_STOCK]([ID_ITEM_CATALOGO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_ESTADO_STOCK_TIPO_STOCK] ON [dbo].[ESTADO_STOCK]([TIPO_STOCK]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_ESTADO_STOCK_TIPO_MOVIMIENTO] ON [dbo].[ESTADO_STOCK]([TIPO_MOVIMIENTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_ORDEN_PRODUCCION_ESTADO_PRODUCCION] ON [dbo].[ORDEN_PRODUCCION]([ESTADO_PRODUCCION]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_ORDEN_PRODUCCION_DETALLE_ID_ORDEN_PRODUCCION] ON [dbo].[ORDEN_PRODUCCION_DETALLE]([ID_ORDEN_PRODUCCION]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_ORDEN_PRODUCCION_DETALLE_ID_ITEM_CATALOGO_PRODUCTO] ON [dbo].[ORDEN_PRODUCCION_DETALLE]([ID_ITEM_CATALOGO_PRODUCTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_ITEM_CATALOGO_COMPONENTE_ID_ITEM_CATALOGO_PADRE] ON [dbo].[ITEM_CATALOGO_COMPONENTE]([ID_ITEM_CATALOGO_PADRE]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_ITEM_CATALOGO_COMPONENTE_ID_ITEM_CATALOGO_COMPONENTE_HIJO] ON [dbo].[ITEM_CATALOGO_COMPONENTE]([ID_ITEM_CATALOGO_COMPONENTE_HIJO]);

-- AddForeignKey
ALTER TABLE [dbo].[ITEM_CATALOGO] ADD CONSTRAINT [ITEM_CATALOGO_ID_CATEGORIA_fkey] FOREIGN KEY ([ID_CATEGORIA]) REFERENCES [dbo].[CATEGORIA]([ID_CATEGORIA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[ITEM_CATALOGO_IMAGEN] ADD CONSTRAINT [ITEM_CATALOGO_IMAGEN_ID_ITEM_CATALOGO_fkey] FOREIGN KEY ([ID_ITEM_CATALOGO]) REFERENCES [dbo].[ITEM_CATALOGO]([ID_ITEM_CATALOGO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[PEDIDO] ADD CONSTRAINT [PEDIDO_ID_CLIENTE_fkey] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [dbo].[CLIENTE]([ID_CLIENTE]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[PEDIDO_DETALLE] ADD CONSTRAINT [PEDIDO_DETALLE_ID_PEDIDO_fkey] FOREIGN KEY ([ID_PEDIDO]) REFERENCES [dbo].[PEDIDO]([ID_PEDIDO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[PEDIDO_DETALLE] ADD CONSTRAINT [PEDIDO_DETALLE_ID_ITEM_CATALOGO_fkey] FOREIGN KEY ([ID_ITEM_CATALOGO]) REFERENCES [dbo].[ITEM_CATALOGO]([ID_ITEM_CATALOGO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[SOLICITUD_ESPECIAL] ADD CONSTRAINT [SOLICITUD_ESPECIAL_ID_CLIENTE_fkey] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [dbo].[CLIENTE]([ID_CLIENTE]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[ESTADO_STOCK] ADD CONSTRAINT [ESTADO_STOCK_ID_ITEM_CATALOGO_fkey] FOREIGN KEY ([ID_ITEM_CATALOGO]) REFERENCES [dbo].[ITEM_CATALOGO]([ID_ITEM_CATALOGO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[ORDEN_PRODUCCION_DETALLE] ADD CONSTRAINT [ORDEN_PRODUCCION_DETALLE_ID_ORDEN_PRODUCCION_fkey] FOREIGN KEY ([ID_ORDEN_PRODUCCION]) REFERENCES [dbo].[ORDEN_PRODUCCION]([ID_ORDEN_PRODUCCION]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[ORDEN_PRODUCCION_DETALLE] ADD CONSTRAINT [ORDEN_PRODUCCION_DETALLE_ID_ITEM_CATALOGO_PRODUCTO_fkey] FOREIGN KEY ([ID_ITEM_CATALOGO_PRODUCTO]) REFERENCES [dbo].[ITEM_CATALOGO]([ID_ITEM_CATALOGO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[ITEM_CATALOGO_COMPONENTE] ADD CONSTRAINT [ITEM_CATALOGO_COMPONENTE_ID_ITEM_CATALOGO_PADRE_fkey] FOREIGN KEY ([ID_ITEM_CATALOGO_PADRE]) REFERENCES [dbo].[ITEM_CATALOGO]([ID_ITEM_CATALOGO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[ITEM_CATALOGO_COMPONENTE] ADD CONSTRAINT [ITEM_CATALOGO_COMPONENTE_ID_ITEM_CATALOGO_COMPONENTE_HIJO_fkey] FOREIGN KEY ([ID_ITEM_CATALOGO_COMPONENTE_HIJO]) REFERENCES [dbo].[ITEM_CATALOGO]([ID_ITEM_CATALOGO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
