-- CreateTable
CREATE TABLE "CONFIGURACION" (
    "ID_CONFIGURACION" INTEGER NOT NULL DEFAULT 1,
    "CANCELAR_PEDIDO_MODO" VARCHAR(20) NOT NULL DEFAULT 'PREGUNTAR',
    "CANCELAR_PEDIDO_DEVOLVER" BOOLEAN NOT NULL DEFAULT true,
    "CANCELAR_ORDEN_MODO" VARCHAR(20) NOT NULL DEFAULT 'PREGUNTAR',
    "CANCELAR_ORDEN_DEVOLVER" BOOLEAN NOT NULL DEFAULT true,
    "FECHA_MODIFICACION" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CONFIGURACION_pkey" PRIMARY KEY ("ID_CONFIGURACION")
);

-- Una sola fila, con los valores iniciales (preguntar al cancelar, con "devolver" marcado).
INSERT INTO "CONFIGURACION" ("ID_CONFIGURACION") VALUES (1);
