-- CreateTable
CREATE TABLE "CONFIGURACION" (
    "ID_CONFIGURACION" INTEGER NOT NULL DEFAULT 1,
    "CANCELAR_PEDIDO" VARCHAR(20) NOT NULL DEFAULT 'PREGUNTAR',
    "CANCELAR_ORDEN" VARCHAR(20) NOT NULL DEFAULT 'PREGUNTAR',
    "FECHA_MODIFICACION" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CONFIGURACION_pkey" PRIMARY KEY ("ID_CONFIGURACION")
);

-- Una sola fila, con los valores iniciales (preguntar al cancelar).
INSERT INTO "CONFIGURACION" ("ID_CONFIGURACION") VALUES (1);
