-- CreateTable
CREATE TABLE "USUARIO_SESION" (
    "ID_USUARIO" BIGINT NOT NULL,
    "VALIDAS_DESDE" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "USUARIO_SESION_pkey" PRIMARY KEY ("ID_USUARIO")
);

-- AddForeignKey
ALTER TABLE "USUARIO_SESION" ADD CONSTRAINT "USUARIO_SESION_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID_USUARIO") ON DELETE CASCADE ON UPDATE NO ACTION;
